### ISSUE TITLE
Alert competitors when there is a new update

### ISSUE THREAD

**Issue by axc** [battlecode/battlecode-client-17#109]
So that people check the changelog. The old client did this by querying http://www.battlecode.org/contestants/latest/.

**Comment by axc** [comment]
On a similar note, it would be useful to also tell competitors which version they currently have, so they know if they are out of date or not.

**Comment by vontell** [comment]
We currently have no versioning information on the client; where and how can we configure this? Through the Config file passed to the constructor for the client I am guessing?
