### ISSUE TITLE
Client sometimes doesn't automatically run match.

### ISSUE THREAD

**Issue by elimbaum** [battlecode/battlecode-client-17#113]
Some users are experiencing an issue wherein running a match via the client (Queue > Run Match) does run the match, and saves the matchfile, but does not automatically load said matchfile and display it. Seems to have appeared suddenly. Deleting and reinstalling client does not fix issue.

**Comment by madan-ram** [comment]
Hi is the problem solved. What was the solution. I am facing aimilar issues.

**Comment by ygina** [comment]
I was able to replicate this issue on a Windows 10 computer. Looking into it, but no fix yet.

**Comment by elimbaum** [comment]
Issue is not yet fixed, though dev team mentioned a bug fix would be released today (hopefully fixing this issue). In the interim, I have navigated around this issue by first manually watching a match (headless) and then adding the file directly to the client.

**Comment by ygina** [comment]
@elimbaum I saw your email about the NotFoundError. It's possible that is a separate issue since I'm replicating the issue here (matchfile isn't automatically displayed) without getting any errors in the console. I'll keep you posted, glad to hear you found a workaround.

**Comment by elimbaum** [comment]
Oh yup, I was conflating those issues. Run Match still doesn't work, but now with no reporting in the dev console.
