### ISSUE TITLE
Client works only the first time after rebuilding

### ISSUE THREAD

**Issue by axc** [battlecode/battlecode-client-17#118]
This happened to a windows 10 user (darthjarjar). After using gradle build, the client works the next time it is opened. But if the client was ever closed and reopened, it wouldn't work again (no players on the dropdown menu) until the next time gradle rebuilt.

**Comment by ygina** [comment]
Neither @jbloxham nor I could replicate this issue on our respective windows 10 computers. It'd be great if we could contact him for more information.

**Comment by axc** [comment]
I'll ask

**Comment by axc** [comment]
Something fixed it!
