### ISSUE TITLE
Execution order not consistent

### ISSUE THREAD

**Issue by DollarAkshay** [battlecode/battlecode-client-17#135]
According to this forum post : http://www.battlecodeforum.org/t/execution-order-in-first-round-broken/390

The execution order is broken in the first round. 

Also it would be nice to know the exact order in which the robots execute and which type of robot group executes first.

**Comment by axc** [comment]
I'm moving the relevant info to the battlecode-server repository. Issue here: https://github.com/battlecode/battlecode-server/issues/374

**Comment by DollarAkshay** [comment]
Alright. Thank You
