### ISSUE TITLE
Speed slider

### ISSUE THREAD

**Issue by HalfVoxel** [battlecode/battlecode-client-17#151]
As opposed to the current four possible speeds (paused, normal speed, fast forward by holding right arrow, fast forward by clicking the fast forward button) it would be very nice if there was a speed slider. Especially when trying to get your bots to avoid bullets it would be very useful to be able to slow down the game to below normal speed or use a speed higher than normal speed but lower than fast forward (in which it is barely possible to see anything imo) and which still uses interpolation (just holding the right arrow key does not).

**Comment by ygina** [comment]
This was a cool idea, thanks! 😃

**Comment by HalfVoxel** [comment]
Nice! When will this be available in the client?

**Comment by ygina** [comment]
10ish minutes? Something like that.
