### ISSUE TITLE
Request: more playback speed settings

### ISSUE THREAD

**Issue by axc** [battlecode/battlecode-client-17#60]
Could be useful to have a few settings in between the current fast and normal settings.

**Comment by vontell** [comment]
Other than what we have now, what else should we add? Do you mean speed of reverse and forward?

**Comment by axc** [comment]
This is super low priority, but sometimes it felt like the main setting was too slow and the fast setting was too fast for what I wanted to do.

**Comment by axc** [comment]
Closing in favor of https://github.com/battlecode/battlecode-client-17/issues/151, which is the same but much better written
