### ISSUE TITLE
setIndicatorLine throws an exception if drawn outside the map

### ISSUE THREAD

**Issue by vontell** [battlecode/battlecode-client-17#94]
See relevant report at http://www.battlecodeforum.org/t/setindicatorline-throws-exception-if-drawing-outside-map/259

**Comment by ygina** [comment]
This is actually not an issue since this is how it's described in the specs. They should use rc.onTheMap() for each location before drawing the line.

**Comment by ygina** [comment]
I suppose we could make it more convenient, but that would have to be changed in server, not here.

**Comment by ygina** [comment]
Actually yea, I'll fix it.
