### ISSUE TITLE
Run match does nothing

### ISSUE THREAD

**Issue by axc** [battlecode/battlecode-client-17#96]
https://gyazo.com/6505af2461dc785531c4338f8787f5f4

Screenshot from competitor "printf". Things work fine with file upload, but not when running match from client. Windows 10.

**Comment by ygina** [comment]
I've been getting this issue inconsistently as well, but I'm not sure what's causing it. When the issue happens, I don't think I got any console output besides more of these:
>websocket.ts:32 WebSocket connection to 'ws://localhost:6175/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

**Comment by ygina** [comment]
If the competitor has the updated client and encounters this error again, it would be helpful if they could press F12 and send us any console output!

**Comment by axc** [comment]
"printf" was able to fix it by setting up the scaffold from scratch. Not too much new info there
